### ISSUE TITLE
Satellite Radio disconnects when sending radio data string to ground

### ISSUE THREAD

**Issue by lcongdon** [silver-sat/Radio_Software#3]
Suspect the Radio data string is too long.

Avionics now truncates the string to 150 bytes, plus prepended "RES GRS " and it is functioning.

Please advise regarding appropriate truncation length for data.

**Comment by lcongdon** [comment]
If Radio requires additional data, it can send multiple responses. Each will be forwarded to the ground.

**Comment by tconrad26** [comment]
The max chunk size is 239 bytes.  The format of an IL2P framed command is: length byte(1) + command byte(1) + header (13) + header parity(2) + data (variable) + data parity(16) + CRC (4).  The total of the non-variable parts is 37.  The chunk header also must be included (3) bringing the total to 40.  
Therefore, the maximum size of the data (the variable part) is 199 bytes.

**Comment by lcongdon** [comment]
The Avionics code prepends the string "RES GRS " to the radio data, reducing the available length

**Comment by tconrad26** [comment]
199 was confirmed.
